In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  
import seaborn as sns

In [10]:
data = pd.read_csv(r"./play_golf_data.csv")

In [14]:
data.describe()

,Unnamed: 0,Weekday,Holiday,Temp,Humidity,Wind,Crowdedness
count,20.00000,20.000000,18.000000,16.000000,16.000000,18.000000,15.000000
mean,9.50000,2.850000,0.055556,25.950000,82.187500,0.277778,0.502667
std,5.91608,1.980829,0.235702,1.801111,10.765493,0.460889,0.209061
min,0.00000,0.000000,0.000000,22.400000,68.000000,0.000000,0.140000
25%,4.75000,1.000000,0.000000,24.600000,74.500000,0.000000,0.350000
50%,9.50000,3.000000,0.000000,26.500000,77.500000,0.000000,0.540000
75%,14.25000,4.250000,0.000000,27.025000,90.750000,0.750000,0.665000
max,19.00000,6.000000,1.000000,28.600000,99.000000,1.000000,0.810000

In [27]:
df = data.drop(columns=['Unnamed: 0'])
df

     Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.1      99.0   0.0     rainy         0.14
1   08-02        1      0.0  26.4       NaN   0.0     sunny          NaN
2   08-03        2      0.0   NaN      96.0   0.0     rainy         0.21
3   08-04        3      0.0  24.1      68.0   0.0  overcast         0.68
4   08-05        4      NaN  24.7      98.0   0.0     rainy         0.20
5   08-06        5      0.0  26.5      98.0   0.0       NaN         0.32
6   08-07        6      0.0  27.6      78.0   0.0     rainy         0.72
7   08-08        0      0.0  28.2       NaN   0.0     rainy         0.61
8   08-09        1      0.0  27.1      70.0   0.0  overcast          NaN
9   08-10        2      1.0  26.7      75.0   NaN     sunny         0.54
10  08-11        3      0.0   NaN       NaN   0.0       NaN          NaN
11  08-12        4      NaN  24.3      77.0   0.0  overcast         0.67
12  08-13        5      0.0  23.1      77.0   1.0     sunny         0.66
13  08-14        6      0.0  22.4      89.0   1.0     rainy         0.38
14  08-15        0      0.0   NaN      80.0   1.0     sunny         0.46
15  08-16        1      0.0  26.5      88.0   1.0     rainy          NaN
16  08-17        2      0.0  28.6      76.0   0.0       NaN         0.52
17  08-18        3      0.0   NaN       NaN   NaN     rainy          NaN
18  08-19        4      0.0  27.0      73.0   1.0  overcast         0.62
19  08-20        5      0.0  26.9      73.0   0.0     sunny         0.81

In [30]:
# Data Cleaning
df_clean = df[df.isnull().sum(axis=1)<4].reset_index(drop=True).copy()

In [31]:
df_clean.head()

    Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0  08-01        0      0.0  25.1      99.0   0.0     rainy         0.14
1  08-02        1      0.0  26.4       NaN   0.0     sunny          NaN
2  08-03        2      0.0   NaN      96.0   0.0     rainy         0.21
3  08-04        3      0.0  24.1      68.0   0.0  overcast         0.68
4  08-05        4      NaN  24.7      98.0   0.0     rainy         0.20

In [33]:
# This code fills in missing values (NaNs) in two specific columns so you don't have "holes" in your data.

HmMean = df_clean['Humidity'].mean()
HdMode = df_clean['Holiday'].mode()[0]
df_clean['Humidity'] = df_clean['Humidity'].fillna(HmMean)
df_clean['Holiday'] = df_clean['Holiday'].fillna(HdMode)
df_clean.head()

    Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0  08-01        0      0.0  25.1   99.0000   0.0     rainy         0.14
1  08-02        1      0.0  26.4   82.1875   0.0     sunny          NaN
2  08-03        2      0.0   NaN   96.0000   0.0     rainy         0.21
3  08-04        3      0.0  24.1   68.0000   0.0  overcast         0.68
4  08-05        4      0.0  24.7   98.0000   0.0     rainy         0.20

In [34]:
# Linear Interpolation
df_clean['Temp'] = df_clean['Temp'].interpolate(method='linear')
df_clean.head()

    Date  Weekday  Holiday   Temp  Humidity  Wind   Outlook  Crowdedness
0  08-01        0      0.0  25.10   99.0000   0.0     rainy         0.14
1  08-02        1      0.0  26.40   82.1875   0.0     sunny          NaN
2  08-03        2      0.0  25.25   96.0000   0.0     rainy         0.21
3  08-04        3      0.0  24.10   68.0000   0.0  overcast         0.68
4  08-05        4      0.0  24.70   98.0000   0.0     rainy         0.20

In [35]:
# Forward/Backward Clean
df_clean['Outlook'] = df_clean['Outlook'].ffill()
df_clean.head()

    Date  Weekday  Holiday   Temp  Humidity  Wind   Outlook  Crowdedness
0  08-01        0      0.0  25.10   99.0000   0.0     rainy         0.14
1  08-02        1      0.0  26.40   82.1875   0.0     sunny          NaN
2  08-03        2      0.0  25.25   96.0000   0.0     rainy         0.21
3  08-04        3      0.0  24.10   68.0000   0.0  overcast         0.68
4  08-05        4      0.0  24.70   98.0000   0.0     rainy         0.20

In [40]:
# .fillna(-1): It looks for every missing value (NaN) in the 'Wind' column and replaces it with the number -1.
df_clean['Wind'] = df_clean['Wind'].fillna(-1)