In [6]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv(r"../DataSets/emp.csv")

In [9]:
df.head()

   empno   ename        job     mgr    hiredate   sal    comm  deptno
0   7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1   7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2   7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3   7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4   7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30

In [10]:
# Target Encoding

df2 = df.copy()

In [11]:
sorted(df2["job"].unique())

['ANALYST', 'CLERK', 'MANAGER', 'PRESIDENT', 'SALESMAN']

In [12]:
df2['job'].value_counts()

job
SALESMAN     4
CLERK        4
MANAGER      3
ANALYST      2
PRESIDENT    1
Name: count, dtype: int64

In [13]:
cols_nums = {"job": {'ANALYST':3, 'CLERK':5, 'MANAGER':2, 'PRESIDENT':1, 'SALESMAN':4}}

In [17]:
df2 = df2.replace(cols_nums)
df2.head()

   empno   ename  job     mgr    hiredate  sal    comm  deptno
0   7839    KING    1     NaN  11/17/2001    1     NaN      10
1   7698   BLAKE    2  7839.0  05/01/2001    2     NaN      30
2   7782   CLARK    2  7839.0  06/09/2001    2     NaN      10
3   7566   JONES    2  7839.0  04/02/2001    2     NaN      20
4   7654  MARTIN    4  7698.0  09/28/2001    3  1400.0      30

In [18]:
def salCatg(salary):
    if salary>=3000:
        r=1
    elif salary>=1500:
        r=2
    else:
        r=3
    return r

In [19]:
df2['sal'] = df2['sal'].apply(salCatg)
df2.head()

   empno   ename  job     mgr    hiredate  sal    comm  deptno
0   7839    KING    1     NaN  11/17/2001    3     NaN      10
1   7698   BLAKE    2  7839.0  05/01/2001    3     NaN      30
2   7782   CLARK    2  7839.0  06/09/2001    3     NaN      10
3   7566   JONES    2  7839.0  04/02/2001    3     NaN      20
4   7654  MARTIN    4  7698.0  09/28/2001    3  1400.0      30

In [20]:
# Label Encoding applies to category data types

df3 = df.copy()
df3.dtypes

empno         int64
ename        object
job          object
mgr         float64
hiredate     object
sal           int64
comm        float64
deptno        int64
dtype: object

In [21]:
df3['job'] = df3["job"].astype('category')
df3.dtypes

empno          int64
ename         object
job         category
mgr          float64
hiredate      object
sal            int64
comm         float64
deptno         int64
dtype: object

In [22]:
sorted(df3["job"].unique())

['ANALYST', 'CLERK', 'MANAGER', 'PRESIDENT', 'SALESMAN']

In [23]:
df3

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10

In [24]:
df3['job1'] = df3['job'].astype('category').cat.codes
df3.head()

   empno   ename        job     mgr    hiredate   sal    comm  deptno  job1
0   7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10     3
1   7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30     2
2   7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10     2
3   7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20     2
4   7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30     4

In [29]:
df3['comm'] = df3['comm'].astype('category').cat.codes
df3.head()

   empno   ename        job     mgr    hiredate   sal  comm  deptno  job1
0   7839    KING  PRESIDENT     NaN  11/17/2001  5000    -1      10     3
1   7698   BLAKE    MANAGER  7839.0  05/01/2001  2850    -1      30     2
2   7782   CLARK    MANAGER  7839.0  06/09/2001  2450    -1      10     2
3   7566   JONES    MANAGER  7839.0  04/02/2001  2975    -1      20     2
4   7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250     3      30     4

In [34]:
# One hot encoder dummy encoding

df4 = df.copy()

In [35]:
sorted(df4["deptno"].unique())

[np.int64(10), np.int64(20), np.int64(30)]

In [36]:
df4['depID']=df4.deptno
df4

    empno   ename        job     mgr    hiredate   sal    comm  deptno  depID
0    7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10     10
1    7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30     30
2    7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10     10
3    7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20     20
4    7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30     30
5    7499   ALLEN   SALESMAN  7698.0  02/20/2001  1600   300.0      30     30
6    7844  TURNER   SALESMAN  7698.0  09/08/2001  1500     0.0      30     30
7    7900   JAMES      CLERK  7698.0  12/03/2001   950     NaN      30     30
8    7521    WARD   SALESMAN  7698.0  02/22/2001  1250   500.0      30     30
9    7902    FORD    ANALYST  7566.0  02/03/2001  3000     NaN      20     20
10   7369   SMITH      CLERK  7902.0  12/17/2000   800     NaN      20     20
11   7788   SCOTT    ANALYST  7566.0  04/19/2007  3000     NaN      20     20
12   7876   ADAMS      CLERK  7788.0  05/23/2007  1100     NaN      20     20
13   7934  MILLER      CLERK  7782.0  01/23/2002  1300     NaN      10     10

In [50]:
# Custom Binary Encoding
import numpy as np
df3["cBE_Code"]=np.where(df3["hiredate"].str.contains("2001"), 1, 0)

In [52]:
df3[["ename", "hiredate", "cBE_Code"]].head(16)

     ename    hiredate  cBE_Code
0     KING  11/17/2001         1
1    BLAKE  05/01/2001         1
2    CLARK  06/09/2001         1
3    JONES  04/02/2001         1
4   MARTIN  09/28/2001         1
5    ALLEN  02/20/2001         1
6   TURNER  09/08/2001         1
7    JAMES  12/03/2001         1
8     WARD  02/22/2001         1
9     FORD  02/03/2001         1
10   SMITH  12/17/2000         0
11   SCOTT  04/19/2007         0
12   ADAMS  05/23/2007         0
13  MILLER  01/23/2002         0

In [53]:
# One Hot Encoder
!pip install category_encoders
import category_encoders as ce

Requirement already satisfied: category_encoders in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from category_encoders) (2.3.5)
Requirement already satisfied: pandas>=1.0.5 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from category_encoders) (2.3.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from category_encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from category_encoders) (0.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\m.aheed siddiqui\new_anaconda\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (25.0)

In [54]:
df5 = df.copy()

In [55]:
encoder = ce.OneHotEncoder(cols='deptno', use_cat_names=True)
df5['depID'] = df5.deptno
data_encoded = encoder.fit_transform(df5)
data_encoded

,empno,ename,job,mgr,hiredate,sal,comm,deptno_10.0,deptno_30.0,deptno_20.0,depID
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,1,0,0,10
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,0,1,0,30
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,1,0,0,10
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,0,0,1,20
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,0,1,0,30
5,7499,ALLEN,SALESMAN,7698.0,02/20/2001,1600,300.0,0,1,0,30
6,7844,TURNER,SALESMAN,7698.0,09/08/2001,1500,0.0,0,1,0,30
7,7900,JAMES,CLERK,7698.0,12/03/2001,950,NaN,0,1,0,30
8,7521,WARD,SALESMAN,7698.0,02/22/2001,1250,500.0,0,1,0,30
9,7902,FORD,ANALYST,7566.0,02/03/2001,3000,NaN,0,0,1,20
10,7369,SMITH,CLERK,7902.0,12/17/2000,800,NaN,0,0,1,20
11,7788,SCOTT,ANALYST,7566.0,04/19/2007,3000,NaN,0,0,1,20
12,7876,ADAMS,CLERK,7788.0,05/23/2007,1100,NaN,0,0,1,20
13,7934,MILLER,CLERK,7782.0,01/23/2002,1300,NaN,1,0,0,10

In [56]:
# Ordinal Encoder
from sklearn.preprocessing import OrdinalEncoder

In [57]:
sorted(df3['deptno'].unique())

[np.int64(10), np.int64(20), np.int64(30)]

In [58]:
ord_enc = OrdinalEncoder()
df3["dno_code"] = ord_enc.fit_transform(df3[["deptno"]])
df3[['ename', "deptno", "dno_code"]].head(14)

     ename  deptno  dno_code
0     KING      10       0.0
1    BLAKE      30       2.0
2    CLARK      10       0.0
3    JONES      20       1.0
4   MARTIN      30       2.0
5    ALLEN      30       2.0
6   TURNER      30       2.0
7    JAMES      30       2.0
8     WARD      30       2.0
9     FORD      20       1.0
10   SMITH      20       1.0
11   SCOTT      20       1.0
12   ADAMS      20       1.0
13  MILLER      10       0.0