In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../DataSets/PlayGolfData.csv")

In [3]:
df_original = df.copy()

# LABEL ENCODING

In [4]:
from sklearn.preprocessing import LabelEncoder

df_label = df_original.copy()

le = LabelEncoder()
df_label['Outlook'] = le.fit_transform(df_label['Outlook'])

df_label.head()
print(df_label.columns)

Index(['Unnamed: 0', 'Date', 'Weekday', 'Month', 'Temperature', 'Humidity',
       'Wind', 'Outlook', 'Crowdedness'],
      dtype='object')

# ONE-HOT ENCODING

In [5]:

df_onehot = df_original.copy()

df_onehot = pd.get_dummies(df_onehot, columns=['Outlook'])

df_onehot.head()
print(df_onehot.columns)

Index(['Unnamed: 0', 'Date', 'Weekday', 'Month', 'Temperature', 'Humidity',
       'Wind', 'Crowdedness', 'Outlook_overcast', 'Outlook_rainy',
       'Outlook_sunny'],
      dtype='object')

# BINARY ENCODING

In [6]:


import category_encoders as ce

df_binary = df_original.copy()

encoder = ce.BinaryEncoder(cols=['Outlook'])
df_binary = encoder.fit_transform(df_binary)

df_binary.head()
print(df_binary.columns)

Index(['Unnamed: 0', 'Date', 'Weekday', 'Month', 'Temperature', 'Humidity',
       'Wind', 'Outlook_0', 'Outlook_1', 'Crowdedness'],
      dtype='object')

# TARGET ENCODING

In [7]:


df_target = df_original.copy()

encoder = ce.TargetEncoder(cols=['Outlook'])
df_target['Outlook'] = encoder.fit_transform(df_target['Outlook'], df_target['Crowdedness'])

df_target.head()

,Unnamed: 0,Date,Weekday,Month,Temperature,Humidity,Wind,Outlook,Crowdedness
0,0,03-25,Mon,Mar,High,Dry,No,62.395727,85
1,1,03-26,Tue,Mar,Low,Humid,Yes,55.243808,30
2,2,03-27,Wed,Mar,High,Dry,Yes,60.934904,65
3,3,03-28,Thu,Mar,Extreme,Dry,Yes,62.395727,45
4,4,03-29,Fri,Mar,Low,Humid,No,55.243808,25

# ORDINAL ENCODING

In [8]:


from sklearn.preprocessing import OrdinalEncoder

df_ordinal = df_original.copy()

oe = OrdinalEncoder(categories=[['Low','High','Extreme']])
df_ordinal[['Temperature']] = oe.fit_transform(df_ordinal[['Temperature']])

df_ordinal.head()

,Unnamed: 0,Date,Weekday,Month,Temperature,Humidity,Wind,Outlook,Crowdedness
0,0,03-25,Mon,Mar,1.0,Dry,No,sunny,85
1,1,03-26,Tue,Mar,0.0,Humid,Yes,rainy,30
2,2,03-27,Wed,Mar,1.0,Dry,Yes,overcast,65
3,3,03-28,Thu,Mar,2.0,Dry,Yes,sunny,45
4,4,03-29,Fri,Mar,0.0,Humid,No,rainy,25

# CYCLIC ENCODING

In [9]:


df_cyclic = df_original.copy()

month_map = {'Jan':1,'Feb':2,'Mar':3,'Apr':4}
df_cyclic['Month_num'] = df_cyclic['Month'].map(month_map)

df_cyclic['Month_sin'] = np.sin(2*np.pi*df_cyclic['Month_num']/12)
df_cyclic['Month_cos'] = np.cos(2*np.pi*df_cyclic['Month_num']/12)

day_map = {'Mon':1,'Tue':2,'Wed':3,'Thu':4,'Fri':5,'Sat':6,'Sun':7}
df_cyclic['Day_num'] = df_cyclic['Weekday'].map(day_map)

df_cyclic['Day_sin'] = np.sin(2*np.pi*df_cyclic['Day_num']/7)
df_cyclic['Day_cos'] = np.cos(2*np.pi*df_cyclic['Day_num']/7)

df_cyclic.head()

,Unnamed: 0,Date,Weekday,Month,Temperature,Humidity,Wind,Outlook,Crowdedness,Month_num,Month_sin,Month_cos,Day_num,Day_sin,Day_cos
0,0,03-25,Mon,Mar,High,Dry,No,sunny,85,3,1.0,6.123234e-17,1,0.781831,0.623490
1,1,03-26,Tue,Mar,Low,Humid,Yes,rainy,30,3,1.0,6.123234e-17,2,0.974928,-0.222521
2,2,03-27,Wed,Mar,High,Dry,Yes,overcast,65,3,1.0,6.123234e-17,3,0.433884,-0.900969
3,3,03-28,Thu,Mar,Extreme,Dry,Yes,sunny,45,3,1.0,6.123234e-17,4,-0.433884,-0.900969
4,4,03-29,Fri,Mar,Low,Humid,No,rainy,25,3,1.0,6.123234e-17,5,-0.974928,-0.222521